server:
  port: 8081

spring:
  application:
    name: customer
  datasource:
    username: 'postgres'
    password: 'root'
    url: jdbc:postgresql://localhost:5432/customer
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
          ddl-auto: create
          show-sql: 'true'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true