server:
  port: 8082
spring:
  application:
    fraud
  datasource:
    username: 'postgres'
    password: 'root'
    url: jdbc:postgresql://localhost:5432/fraud
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
          ddl-auto: create
          show-sql: 'true'